# Generated by Django 2.2.9 on 2020-02-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
