# Generated by Django 2.2.9 on 2020-01-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='descripcion',
            new_name='observacion',
        ),
    ]
