# Generated by Django 2.2.9 on 2020-01-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_auto_20200121_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
    ]
